export  'package:flutter/material.dart';
export './const.dart';
export 'package:bewp_life/view/forgot-password/forgot-password.dart';
export 'package:bewp_life/view/forgot-password/verify-pin.dart';
export 'package:bewp_life/view/startup-screens/login-email.dart';
export 'package:bewp_life/view/startup-screens/welcome-page.dart';
export 'package:bewp_life/view/startup-screens/registerApp.dart';
export './view/home-screens/home-page.dart';
export 'package:bewp_life/extensions/extension.dart';